### ISSUE TITLE
R script that subsets tables to only contain representative genomes

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pf-gtdb-analyses#1]
Add an R *script* (i.e. not an Rmd) to `scripts` that reads all the feather files and the `gtdb_metadata.tsv` and outputs new feather files that only contain data referring to the species representative genomes.

**Comment by GhadaNOUAIRIA** [comment]
the list of representatives is in a file called sp_clusters. tsv (not gtdb_metadata.tsv), 
my script reads representatives directly from sp_clusters.tsv and does not use gtdb_metadata.tsv

**Comment by erikrikarddaniel** [comment]
OK. Then we need to add download of this file in the `data/Makefile`.

**Comment by GhadaNOUAIRIA** [comment]
We need to download it and publish to results also. 
Maybe we can add this file to the GetMetadata process in main.nf? Or should it have its own process?

**Comment by erikrikarddaniel** [comment]
Since this is not part of the workflow it only needs to be downloaded by the build process in this repo. (Another question is whether it would be better as part of the workflow, but lets leave it as it is now.)

**Comment by GhadaNOUAIRIA** [comment]
added to Makefile
