### ISSUE TITLE
Let's keep Rmd files in the root directory

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pf-gtdb-analyses#7]
My plan was to solve some issues with how Rmarkdown deals with paths by having the Rmd files in the root directory of the project. So, move the `NrdR.Rmd` and delete the `Rmd` directory. (If there's nothing else in `Rmd` I think it will automatically be removed.)

**Comment by GhadaNOUAIRIA** [comment]
I know the issue you are referring to. 
Done for NrdR.Rmd and also for select_saATP-cones.Rmd (on sa_ATP_cones branch).

**Comment by erikrikarddaniel** [comment]
Great that you keep the Rmds in separate branches. Let's do this until we start writing the manuscript and then we pull in each branch when we need it.
